# Generated by Django 6.0.3 on 2026-03-11 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficlog',
            name='ai_analysis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trafficlog',
            name='protocol',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='trafficlog',
            name='result',
            field=models.CharField(max_length=100),
        ),
    ]
