# Generated by Django 6.0.3 on 2026-03-11 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0002_trafficlog_ai_analysis_alter_trafficlog_protocol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficlog',
            name='attacker_ip',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
