# Generated by Django 6.0.3 on 2026-03-12 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0003_trafficlog_attacker_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficlog',
            name='attack_type',
            field=models.CharField(default='Normal Traffic', max_length=100),
        ),
    ]
